services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: tyr020617
      MYSQL_DATABASE: golanguage_db
    ports:
      - "3307"
    networks:
      - backend

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

